import { PageHeader } from "@/components/viz/page-header";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import {
  Database, GitBranch, Scale, Dices, Link2, ShieldAlert, Waves, Triangle, Timer, FlaskConical,
} from "lucide-react";
import type { ReactNode } from "react";

const LIMITATIONS: { icon: ReactNode; title: string; body: ReactNode }[] = [
  {
    icon: <Database className="h-4 w-4" />,
    title: "The dataset is synthetic",
    body: (
      <>
        Every row in CommerceLens was generated by a Python script (<code className="font-mono text-xs">data/generate_dataset.py</code>)
        that intentionally encodes realistic relationships (e.g. add-to-cart raising purchase probability). It is
        useful for demonstrating analytical method end-to-end, but it was <em>designed</em> to show these patterns
        &mdash; it does not prove that a real marketplace behaves this way. Real transactional data would need to be
        substituted to draw operational conclusions.
      </>
    ),
  },
  {
    icon: <GitBranch className="h-4 w-4" />,
    title: "The data is observational, not experimental",
    body: (
      <>
        No variable here was randomly assigned by an A/B test. Discount exposure, campaign exposure, device, and
        channel are all outcomes of the generative model&rsquo;s own logic (and, in a real business, of customer choice
        and targeting rules), not of a controlled experiment. Associations reported throughout the site describe
        patterns <em>in this sample</em> — they do not isolate a causal effect.
      </>
    ),
  },
  {
    icon: <Scale className="h-4 w-4" />,
    title: "Correlation is not causation",
    body: (
      <>
        Every association page on this site (Association, Decision Lab, Probability Engine) is written to avoid
        causal language. A statement like &ldquo;purchase probability is higher among discount-exposed
        sessions&rdquo; describes a conditional relationship in the data; it does not mean the discount caused the
        purchase. Confounding variables (e.g. a customer&rsquo;s underlying intent driving both discount-seeking and
        purchase) are plausible and were not ruled out.
      </>
    ),
  },
  {
    icon: <Dices className="h-4 w-4" />,
    title: "Empirical probabilities depend on the sample",
    body: (
      <>
        Every probability shown (P(Purchase | Cart), independence checks, etc.) is computed from this specific
        60,000-session sample. A different sample &mdash; or the same population at a different point in time &mdash;
        would produce different empirical probabilities. None of these figures should be read as a fixed population
        parameter.
      </>
    ),
  },
  {
    icon: <Link2 className="h-4 w-4" />,
    title: "Independence checks are empirical comparisons, not proofs",
    body: (
      <>
        The Independence Check page compares P(A∩B) to P(A)&middot;P(B) in the observed sample. A small difference is
        evidence <em>consistent with</em> independence under this sample &mdash; it is not a formal statistical test
        (e.g. a chi-squared test with a p-value) and should not be presented as definitive proof that two events are
        independent in general.
      </>
    ),
  },
  {
    icon: <ShieldAlert className="h-4 w-4" />,
    title: "Binomial assumptions may not perfectly hold in real e-commerce traffic",
    body: (
      <>
        The Conversion Forecast Simulator assumes a fixed number of trials, exactly two outcomes, a constant success
        probability, and independent/IID trials. Real traffic violates several of these: conversion probability
        shifts with seasonality and campaigns, and a single customer&rsquo;s repeat sessions are not independent of
        each other. The simulator is a useful planning approximation, not an exact model of live traffic.
      </>
    ),
  },
  {
    icon: <Timer className="h-4 w-4" />,
    title: "The exponential assumption is a modeling choice, not a verified fact",
    body: (
      <>
        The Continuous Distribution Lab models time-between-purchases as exponential for illustration, including its
        memoryless property. Real purchase intervals often show clustering, trend, and habit effects that a plain
        exponential model does not capture. The lab compares the model&rsquo;s mean to one empirical anchor
        (observed average days since last order) but does not claim a formal goodness-of-fit test was run.
      </>
    ),
  },
  {
    icon: <Triangle className="h-4 w-4" />,
    title: "The triangular distribution is assumption-driven",
    body: (
      <>
        The delivery-time triangular model is parameterized by a chosen minimum, most-likely, and maximum estimate
        &mdash; a common approach when historical data is sparse — rather than fit to a large empirical delivery-time
        sample. Its shape is only as good as those three inputs.
      </>
    ),
  },
  {
    icon: <Waves className="h-4 w-4" />,
    title: "Distributional and independence assumptions throughout",
    body: (
      <>
        Several calculations (binomial, hypergeometric, uniform, exponential) rest on textbook assumptions — fixed
        probability, sampling without replacement from a known finite pool, uniform density over a bounded interval,
        or independent trials. Each of these is stated explicitly on its page and flagged as a <strong>Model
        Simulation</strong> where it is a hypothetical forward-looking scenario rather than a re-derivation from raw
        rows.
      </>
    ),
  },
  {
    icon: <FlaskConical className="h-4 w-4" />,
    title: "Synthetic relationships were generated, not discovered",
    body: (
      <>
        Because the relationships in this dataset (e.g. discount exposure raising purchase probability) were written
        into the generator, finding them again through analysis demonstrates correct <em>method</em>, not
        discovery of a real marketplace insight. The purpose of CommerceLens is to showcase the analytical workflow
        — descriptive statistics, association, probability, distributions, decision framing — end to end on a
        dataset with known, intentional structure.
      </>
    ),
  },
];

export default function LimitationsPage() {
  return (
    <div className="space-y-8">
      <PageHeader
        eyebrow="Read this before citing any number"
        title="Limitations"
        description="CommerceLens is a demonstration of analytical method, not a market research report. This page lists the boundaries of what the dataset and the analyses on this site can and cannot support."
      />

      <div className="grid gap-4 md:grid-cols-2">
        {LIMITATIONS.map((l) => (
          <Card key={l.title}>
            <CardHeader className="flex-row items-center gap-2 space-y-0">
              <span
                className="flex h-7 w-7 shrink-0 items-center justify-center rounded-md"
                style={{ backgroundColor: "color-mix(in srgb, var(--series-1) 12%, transparent)", color: "var(--series-1)" }}
              >
                {l.icon}
              </span>
              <CardTitle className="text-sm">{l.title}</CardTitle>
            </CardHeader>
            <CardContent className="text-sm leading-relaxed text-muted-foreground">{l.body}</CardContent>
          </Card>
        ))}
      </div>

      <Card className="border-[var(--status-warning)]/40 bg-[color-mix(in_srgb,var(--status-warning)_6%,transparent)]">
        <CardContent className="pt-6 text-sm leading-relaxed">
          <strong>In one sentence:</strong> every number on this site is arithmetically correct given the dataset it
          was computed from, and every dataset relationship was intentionally generated to be realistic — but
          &ldquo;realistic&rdquo; is not the same as &ldquo;real,&rdquo; and no claim here should be treated as
          evidence about an actual marketplace, actual customers, or actual causal effects.
        </CardContent>
      </Card>
    </div>
  );
}
